///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String animationsLoaderAnimation = 'assets/animations/loader_animation.json';
  static const String fontsSoraBold = 'assets/fonts/Sora-Bold.ttf';
  static const String fontsSoraExtraBold = 'assets/fonts/Sora-ExtraBold.ttf';
  static const String fontsSoraExtraLight = 'assets/fonts/Sora-ExtraLight.ttf';
  static const String fontsSoraLight = 'assets/fonts/Sora-Light.ttf';
  static const String fontsSoraMedium = 'assets/fonts/Sora-Medium.ttf';
  static const String fontsSoraRegular = 'assets/fonts/Sora-Regular.ttf';
  static const String fontsSoraSemiBold = 'assets/fonts/Sora-SemiBold.ttf';
  static const String fontsSoraThin = 'assets/fonts/Sora-Thin.ttf';
  static const String iconsArrowLeft = 'assets/icons/arrow_left.svg';
  static const String iconsBackButton = 'assets/icons/back_button.svg';
  static const String iconsBan = 'assets/icons/ban.svg';
  static const String iconsClose = 'assets/icons/close.svg';
  static const String iconsDelete = 'assets/icons/delete.svg';
  static const String iconsFavorite = 'assets/icons/favorite.svg';
  static const String iconsFavoriteButton = 'assets/icons/favorite_button.svg';
  static const String iconsFavoriteGreen = 'assets/icons/favorite_green.svg';
  static const String iconsFavoriteGrey = 'assets/icons/favorite_grey.svg';
  static const String iconsNoResult = 'assets/icons/no_result.svg';
  static const String iconsSearch = 'assets/icons/search.svg';
}
